# Generated by Django 5.0.2 on 2024-02-25 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_avatar_user_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name=" Подписки",
            ),
        ),
    ]
