# Generated by Django 5.0.2 on 2024-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(max_length=100, unique=True, verbose_name="Почта"),
        ),
    ]
