# Generated by Django 5.0.2 on 2024-02-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_publication_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
